### ISSUE TITLE
Error when computing one channel

### ISSUE THREAD

**Issue by bonaime** [eost/clb-noise-analysis#4]
````code
No PAZ found for XX.BUFF.10
No pickle file found for XX.BUFF.10.HHE (looked for /private/tmp/clb-noise-analysis/PKL/XX.BUFF.10.HHE.pkl)
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.201
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.202
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.203
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.204
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.205
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.206
reading /Users/bonaime/Google Drive/RESIF IPGP Geoscope/Prospection/Par5/Buffon/SDS/2016/XX/BUFF/HHE.D/*.207
Traceback (most recent call last):
Traceback (most recent call last):
  File "./qc.py", line 1101, in <module>
    main()
  File "./qc.py", line 1078, in main
    S.add(all_streams)
  File "./qc.py", line 423, in add
    success = self.__process(slice)
  File "./qc.py", line 481, in __process
    paz_simulate=None, simulate_sensitivity=False)
  File "<decorator-gen-19>", line 2, in simulate
  File "/Users/bonaime/anaconda/envs/obspy/lib/python2.7/site-packages/obspy/core/trace.py", line 232, in _add_processing_info
    result = func(*args, **kwargs)
  File "/Users/bonaime/anaconda/envs/obspy/lib/python2.7/site-packages/obspy/core/trace.py", line 1377, in simulate
    simulate_sensitivity=simulate_sensitivity, **kwargs)
  File "/Users/bonaime/anaconda/envs/obspy/lib/python2.7/site-packages/obspy/signal/invsim.py", line 608, in simulate_seismometer
    data /= paz_remove['sensitivity']
KeyError: u'sensitivity'
````

Qc.py works for HHZ and HHN but not for HHE !

**Comment by bonaime** [comment]
It was a dataless problem without sensitivity blockett
